### ISSUE TITLE
Page margin setting cropping image

### ISSUE THREAD

**Issue by cruisetheblues** [MarginallyClever/Makelangelo-software#176]
When importing an image after using the page margin slider, the image is cropped to fit in the page margin box instead of being resized. This issue was not present in previous releases as far as I'm aware.

**Comment by i-make-robots** [comment]
In previous versions the image was sized downwards fit entirely within the
margins.  Now it is sized up to fill the page, tho some cropping may
occur.  In a future version I want to let the user adjust a preview and the
convert the image, so this issue will go away.

On Sat, Apr 30, 2016 at 7:04 PM, cruisetheblues <notifications@github.com>
wrote:

> When importing an image after using the page margin slider, the image is
> cropped to fit in the page margin box instead of being resized. This issue
> was not present in previous releases as far as I'm aware.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo/issues/176>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by i-make-robots** [comment]
I have internal methods to move and resize an image before it is converted, but I have no UX pipeline to make it happen.  That is to say there is an "open an image" step and a "convert image" step and there should be a "position image" step between the two... but there isn't.  It would require a serious rethink of the system to add such a step.

**Comment by i-make-robots** [comment]
Fixed in 4b829857d3eb24dac2be24fa24ca2dbd26ea939c.  I misread this bug.  I thought you wanted to arbitrarily position and scale image before conversion.  It was adding a way to (A) scale the image to fill the paper or (B) fit the image on the paper when I realized what you were talking about.  Wow!  Only 16 months!
