### ISSUE TITLE
add auto-update feature

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-Software#196]
shitty example:
http://www.dreamincode.net/forums/topic/190944-creating-an-updater-in-java/

**Comment by virtuoushub** [comment]
I [commented](https://github.com/MarginallyClever/Makelangelo-Software/issues/84#issuecomment-100493368) on some other examples in #84.

**Comment by i-make-robots** [comment]
Doh.  duplicate issue!
