### ISSUE TITLE
7.9.1 doesn't save pulley diameter settings for custom machine

### ISSUE THREAD

**Issue by b3nno** [MarginallyClever/Makelangelo-software#213]
7.9.1 doesn't save pulley diameter settings for custom machine.
wenn I set a value for pulley diameter, it doesn't save in the machine. 
I checked it with the D2 command. I allways get 0.35 for both pulleys...

**Comment by i-make-robots** [comment]
how the heck is it 0.35?  the default is 1.27323954

**Comment by i-make-robots** [comment]
Duplicate of #212
