### ISSUE TITLE
Release 33 confusion?

### ISSUE THREAD

**Issue by tjhawkey** [MarginallyClever/Makelangelo-software#228]
All three versions seem to claim that there's a newer version. Which is actually the latest?
Thx

**Comment by i-make-robots** [comment]
Good question!  All three are identical.  When I make a new release it is supposed to trigger web hooks that update my online store.  The hook was broken.  New releases were made in an attempt to fix the problem, which has now been resolved.  I don't know the best way to remove the duplicates so I'm just leaving them.
