### ISSUE TITLE
Open GL error

### ISSUE THREAD

**Issue by tjhawkey** [MarginallyClever/Makelangelo-software#232]
I get an "Open GL ES Error" when I start Makelangelo 7.15.5
The content is "Can't find the name of Intel ICD OpenGL driver"
Asus Q504 laptop (integrated intel graphics, but Asus driver)
If I click "OK" about 10 times, the software starts and seems to function OK.

UPDATE: I forced an update to the latest intel driver and no longer get the error message.

**Comment by i-make-robots** [comment]
Does this help?

https://www.drivereasy.com/knowledge/solved-cant-find-the-name-of-intel-icd-opengl-driver/

**Comment by tjhawkey** [comment]
Thanks for the suggestion.
I manually forced my laptop to use the latest intel driver and that fixed
the Makelangelo error, though it made Solidworks crash.
I have to look into the graphics settings and see if I can fix Solidworks.

TIm
