### ISSUE TITLE
SVG export not centered to paper, paper size wrong

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#236]
since 7.15.*?

**Comment by i-make-robots** [comment]
@jsecondo if you can try the developer version and confirm?  Also try with landscape paper rotation.  paper in inkscape should make machine size in makelangelo, drawing should be centered.

**Comment by jsecondo** [comment]
Changing to landscape works quite alright. Did recentering on the page by hand.

The SVG I was trying was a CMYK. The SVG contains all the lines but doesn't discriminate on the color, right? So to have a SVG of each color component I have to do the separation and then treat each component separately. Do I have a way to replicate each color drawing from the CMYK style? Guess that in GCODE I'll find the way.

**Comment by jsecondo** [comment]
Did some testing with WANDERER and CMYK option with 50000 lines (by the way, which is the limit?)

First test didn't quite get it 
Original1
<img width="585" alt="color_wheel" src="https://user-images.githubusercontent.com/396985/41187482-7a24b74c-6b80-11e8-936b-988b9816e749.png">
Produced-->>
![wandercmyk](https://user-images.githubusercontent.com/396985/41187489-982567fa-6b80-11e8-97d2-2c052a8c1786.png)

Original2:
![paleta](https://user-images.githubusercontent.com/396985/41187486-89d96f70-6b80-11e8-8144-ccfe4c158da9.png)

Produced---->
![wandercmyk2](https://user-images.githubusercontent.com/396985/41187491-a4a4f306-6b80-11e8-94dd-0d22fee5c660.png)

The first image didn't show a lot of cyan. The second one was more balanced and imitated pretty well the colors of the original.

**Comment by i-make-robots** [comment]
Wander CMYK is pretty new and pretty terrible.  Please keep issues separate so they can be dealt with correctly.

**Comment by i-make-robots** [comment]
created issue #237 for CMYK Wander.
