### ISSUE TITLE
Export GCode

### ISSUE THREAD

**Issue by mikepkes** [MarginallyClever/Makelangelo-software#24]
There does not appear to be an export gcode option in the java GUI.

**Comment by gouessej** [comment]
Don't store the GL instances into fields. You can get them by using GLAutoDrawable.getGL() or GLContext.getGL(), refrain yourself from passing them if possible. Not doing so can lead to subtle bugs when the GL instance becomes invalid. It's not the same for the GLU objects as they use GL objects at creation mostly to choose a GLU subclass with the correct abilities.
