### ISSUE TITLE
Command-line gcode generator

### ISSUE THREAD

**Issue by mikepkes** [MarginallyClever/Makelangelo-software#25]
for more automated prints or integration into other projects, it would be nice to be able to run all the generator logic in a non-gui mode.

**Comment by mouseas** [comment]
Depending on how this is implemented, it could make adding new converters/generators much easier; each converter/generator is its own command-line program, and the GUI calls each through command-line instead of internally.

**Comment by i-make-robots** [comment]
imho converters and generators shouldn't be producing gcode at all.  this is a mistake I made ages ago that has tenaciously held on.  

g&c should produce some internal vector format and a separate set of classes should take the internal format, then convert that to gcode, svg, dxf, or bitmap.  this would also mean that the rendering engine could use the vector format (currently the render engine parses gcode.  lol wut?)

**Comment by i-make-robots** [comment]
in 7.25.0, the UX is being separated from the core logic.  A CLI needs to be built for the node-based system... the ability to run headless is finally approaching.
