### ISSUE TITLE
Some of the converters draw a line from 0,0

### ISSUE THREAD

**Issue by mishafarms** [MarginallyClever/Makelangelo-software#257]
Dan,
  While playing with the Makelangelo software. I came across some times when convert an image that there is a line drawn from 0,0 to the beginning of the drawing. Spiral pulse was one.

I have fixes for these. If you want them.

Michael (github@mishafarms)

**Comment by i-make-robots** [comment]
Yes please!

**Comment by i-make-robots** [comment]
which converters have the issue, please?

**Comment by mishafarms** [comment]
I thought I gave you the code already. One of the convertors was Pulsing Spiral and the other was SandyNoble.

If you look at my repository in the pi4 branch you should see all the fixes there. 

My repository isn't quite up to date with yours at the moment. I will merge in a few days. I am a little sick and playing with something else at the moment.

Michael
