### ISSUE TITLE
DXF export upside down

### ISSUE THREAD

**Issue by Jip-Hop** [MarginallyClever/Makelangelo-software#281]
Fibonacci Spiral Fractal generated with latest release of Makelangelo: Makelangelo-7.23.0-with-dependencies.jar:

<img width="1440" alt="Fibonacci Spiral Fractal generated in Makelangelo" src="https://user-images.githubusercontent.com/2871973/85221830-5d10f180-b3b7-11ea-9b19-e5da8e66595a.png">

Upside down when exported as DXF and imported again:

<img width="1440" alt="Fibonacci Spiral Fractal upside down when exported and imported as DXF" src="https://user-images.githubusercontent.com/2871973/85221854-95183480-b3b7-11ea-98dd-13c1cc7244fe.png">

DXF import the correct way up, so the issue has to be with the export function.

**Comment by i-make-robots** [comment]
Is this better now, @Jip-Hop ?

**Comment by Jip-Hop** [comment]
Yes, you fixed it!
