### ISSUE TITLE
Nightly builds by CI for testers that need the dev edition.

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#295]
After CI runs and passes,
package final jar into zip file with release contents,
publish release as a daily build,
remove old builds if old > 3 builds.

**Comment by i-make-robots** [comment]
Here is the first one!  https://github.com/MarginallyClever/Makelangelo-software/releases/download/7.23.0/makelangelo_windows-nightly-20200702-5f2ca4.zip

As I understand it instant releases will appear in the most recent release, and no more than three instant releases will exist at a time.

**Comment by bjbsquared** [comment]
I dont know JAVA or how the IDE works. Looks like there are plugins it can't find:
![errors](https://user-images.githubusercontent.com/2354263/86484565-1ce93180-bd1c-11ea-9d88-d5d99503bfd9.PNG)

**Comment by i-make-robots** [comment]
You shouldn't have to run Eclipse if you're using a nightly build.  the zip file *is* a JAR file.  rename it and run it.  I'll see what I can do to keep the .jar name on each nightly build.

**Comment by i-make-robots** [comment]
Corrected.  Please try https://github.com/MarginallyClever/Makelangelo-software/releases/download/Nightly/makelangelo_windows-nightly-20200703-f8284b.jar
