### ISSUE TITLE
use maven wrapper to ease first build

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#331]
**Is your feature request related to a problem? Please describe.**
In the README, it is stated that eclipse should be used to import the project in order to build it.
It could be easier to use maven to build it directly. Moreover, the [maven wrapper](https://github.com/takari/maven-wrapper) could be added to the project. I see that is there are some file of a previous installation in the `java/maven/wrapper`.

**Describe the solution you'd like**
If you want, I can add it and cleanup old files

**Describe alternatives you've considered**
none

**Comment by i-make-robots** [comment]
I'm bad at maven management.  Go ahead!
