### ISSUE TITLE
Infill for SVG closed regions

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#351]
SVGs have areas that are closed and supposed to be filled with color.
Find said areas and run an algorithm to fill them in at load time.

**Comment by i-make-robots** [comment]
Filling a single convex closed shape is not terrible.
a concave shape is harder.
a twisted shape (think spirograph) is harder still.
A donut?  I don't even know where to start doing that one right.  Like... what do you do if there are filled and unfilled donuts in the same SVG?  How do you know which shapes are compound inside each other?

**Comment by PPAC37** [comment]
It seems to me that this notion is also lacking in Generator_Text ... but I have not yet fully explored and understood the code of this class.
https://github.com/MarginallyClever/Makelangelo-software/blob/8fe5def5b94775d3ba8b3a75c70718d60a027356/src/main/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_Text.java#L28

**Comment by i-make-robots** [comment]
In a more general sense there should be a system that
- receives a Turtle
- confirms the path forms a closed loop
- builds a new turtle that is the infill for the first turtle and does not modify the original

then the calling method can choose to merge the two turtles together, draw them side-by-side, whatever.

**Comment by i-make-robots** [comment]
8515e85c creates a rough draft of this system.

**Comment by i-make-robots** [comment]
d5e5b6f9 results:
![2021-12-22-01](https://user-images.githubusercontent.com/1464454/147162621-58110f83-50f2-475b-a48f-15f1673d9a35.PNG)
![2021-12-22-02](https://user-images.githubusercontent.com/1464454/147162624-247815b9-ad08-4f83-88e4-ad37fef78c59.PNG)

**Comment by i-make-robots** [comment]
02c5ecee fixes missing string

**Comment by i-make-robots** [comment]
This naive approach will fill *all* closed loops in the Turtle.  Because it assumes closed areas do not overlap there may be some cases like this:
![2021-12-22-03](https://user-images.githubusercontent.com/1464454/147162994-0b9e7a19-88d3-4709-986a-961a4179c4ea.PNG)
![2021-12-22-04](https://user-images.githubusercontent.com/1464454/147162996-61196709-6ff7-4807-80b3-b2f17f5e093c.PNG)

**Comment by i-make-robots** [comment]
....and now I don't have an SVG with which to test.

**Comment by PPAC37** [comment]
Correct me if I'm wrong:

An SVG (for example with two squares) or Text (a word ex "Hëllo") are composed of sub-elements.
For an SVG the sub-elements are the shapes (the two squares) and for the text are the characters.
When we transform them in the turtle model (simple commands), we lose the notions of groups and subgroups.
For me the difficulty comes from there.

Therefore :

If the turtle does not happen to be with the notion of group (or composition of turtle sub-elements) two sub-elements which intertwine, will be difficult, or even impossible, to separate correctly (distinction lost cause no group separation).

(As when we try to decompile source code, as we have lost the high level abstractions, it often becomes impossible to find the high level logic (object model) against the code in assembler (instruction for the microcontroller).)

**Comment by PPAC37** [comment]
for the moment the only thing which seems to implement a notion of group (here by color) in Tortule :
https://github.com/MarginallyClever/Makelangelo-software/blob/165af0cee16ce89a7b02d6066832920b480091c5/src/main/com/marginallyclever/makelangelo/turtle/Turtle.java#L394
it would be something like that, but for a group or layer abstraction, it would be necessary to simplify the problem (no search for, who owns this enclosed loop, between two different groups). (this will create complications but seems imperative to me)

**Comment by PPAC37** [comment]
I forgot to say "too cool" for the filling (even if it does not handle complex cases it is already very nice).

Then it seems that something is missing from the interpretation of an SVG because if I convert my SVG to dxf then I have closed loops filled after the infill but not with the original SVG.
first = SVG + infill, second = dxf + infill.
![image](https://user-images.githubusercontent.com/94939582/147272589-e7e0b315-aef9-4d88-85bb-bcebab837b85.png)

**Comment by i-make-robots** [comment]
try reorder before infill.  probably DXF runs a reorder before finishing and SVG does not.

Now that I can fill in turtles I can make subgroups into turtles and fill them - in the middle of loading the SVG.  The tools are all available, they have to be put in the right sequence.

**Comment by i-make-robots** [comment]
You're right about split by tool change.  infill currently doesn't care about tool changes and will smash everything to one layer.  not a problem, just.... whoops.

**Comment by i-make-robots** [comment]
8384766d added support for tool changes.

**Comment by i-make-robots** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes
Ugh.  Fill spec is some bull. shit.
