### ISSUE TITLE
Importing an .svg with Ellipses turns them into Triangles

### ISSUE THREAD

**Issue by GereonPlaettner** [MarginallyClever/Makelangelo-software#359]
**Steps to make the bug happen**
1. Create an ellipse in processing.
2. Export it to .svg
3. Import the .svg into the makelangelo software

**What was supposed to happen**
An ellipse should stay elliptical.

**Platform (please complete the following information):**
 - Version: 7.28.2
 - OS: Windows 10
 - Robot model: Makelangelo 5

**Log file**
[log.txt](https://github.com/MarginallyClever/Makelangelo-software/files/7532674/log.txt)

**Additional context**
Using Inkscape to ungroup and convert to path and exporting as dxf12 resolves this in a roudnabout way.

![image](https://user-images.githubusercontent.com/92274990/141657698-3c10bbb4-0d68-40a0-b62a-1f2567fb8c72.png)

[filename.zip](https://github.com/MarginallyClever/Makelangelo-software/files/7532671/filename.zip)

**Comment by i-make-robots** [comment]
Please try the nightly build and let me know if that's better, too much detail in each circle... your thoughts welcome.

**Comment by GereonPlaettner** [comment]
Issue solved for me!
