### ISSUE TITLE
Scale strange deformation

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#380]
**Steps to make the bug happen**
1. Load an SVG
2. Go to 'Tools'
2. Click on 'Scale'
3. Increment the width by 1 unit
4. Click on the lock icon
5. Increment the height with the arrow up button
6. Decrement the height with the arrow down button
7. the picture's height on the main window is still increasing
![image](https://user-images.githubusercontent.com/23615562/146934058-bd897ba4-7d90-4dfb-8106-9a48e31d2e3f.png)

**What was supposed to happen**
The height of the picture should decrease

**Platform (please complete the following information):**
 - Version: 7.30.2
 - OS: mac os 11.6
 
**Log file**
[log.txt](https://github.com/MarginallyClever/Makelangelo-software/files/7755436/log.txt)

**Additional context**
If playing with the percent drop down menu, the picture is messed up and it not possible to reset the size

**Comment by i-make-robots** [comment]
Confirmed.
