### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#386]
**Steps to make the bug happen**
1. Import a new picture
2. See error
![image](https://user-images.githubusercontent.com/23615562/147074926-4401ebd2-632b-4797-b004-12a7b51f31f4.png)

**What was supposed to happen**
I think that some translations are missing

**Platform (please complete the following information):**
 - Version: master 8fe5def5b94775d3ba8b3

**Comment by i-make-robots** [comment]
Added missing strings to english.xml in b2ad5bb7
![Capture](https://user-images.githubusercontent.com/1464454/147134016-68ee49b5-f835-4e9c-9e68-baf85bce8228.PNG)

**Comment by i-make-robots** [comment]
Oh damnit, the message for teh PR is right there.... my bad.
