### ISSUE TITLE
Add QOI image format support

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#415]
**Is your feature request related to a problem? Please describe.**
Add support for new QUI image format

**Describe the solution you'd like**
see https://github.com/saharNooby/qoi-java

**Describe alternatives you've considered**
None

**Additional context**
https://tech.slashdot.org/story/21/12/25/0618218/quite-ok-image-format-qoi-coming-to-a-graphics-program-near-you

**Comment by PPAC37** [comment]
interesting, for me it's new, ... so we'll have to play with it;)

**Comment by i-make-robots** [comment]
tested with https://github.com/saharNooby/qoi-java/blob/main/src/test/resources/dice.qoi :
![Capture101](https://user-images.githubusercontent.com/1464454/147418811-c9ac4341-5e75-428e-abe5-219b81eabbb3.PNG)

**Comment by PPAC37** [comment]
Well done !
