### ISSUE TITLE
Strange behavior of SelectTextArea in the SelectPanel on a window resize.

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#417]
To summarize the good use of class Select* still escapes me. 

Is there an example with a SelectTextArea ( a Select containing a JTextArea in a JScrollPane ) that doesn't have a strange behavior?

Strange behavior of SelectTextArea in the SelectPanel when resizing the SelectPanel : 
Menu bar -> "Generate art" -> "Your message here" and try to resize multiple times the window "Your message here".

**Comment by i-make-robots** [comment]
Good catch, @PPAC37 !

**Comment by PPAC37** [comment]
Well done!
I was completely lost on the source of the problem. and therefore the solution. And you correct that, in less than 10 minutes.

**Comment by i-make-robots** [comment]
It never hurts to ask the guy who's been reading the code since day 1 :)
