### ISSUE TITLE
Paper Margin should work like scale (with mm/% option)

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#428]
**Is your feature request related to a problem? Please describe.**
Margin with a slider works.  Could be better.

**Describe the solution you'd like**
Scale image offers % or mm choices, in both X and Y.  Margin could do the same for more fine grain control.  It should also remember each setting as a preference.

**Describe alternatives you've considered**
Leaving it alone?

**Additional context**
current paper settings
![paper](https://user-images.githubusercontent.com/1464454/147697354-ab497606-4210-4663-8836-c8c301ec5e9e.PNG)

current scale settings
![scale](https://user-images.githubusercontent.com/1464454/147697357-e999b191-4396-4864-b1a7-5530706939c7.PNG)

also note vastly different layout and margins.  consistent look and feel! :(

**Comment by i-make-robots** [comment]
I thouhght "<- ->" was replaced with "landscape"?

**Comment by PPAC37** [comment]
> I thouhght "<- ->" was replaced with "landscape"?

in https://github.com/MarginallyClever/Makelangelo-software/pull/369 ?

**Comment by coliss86** [comment]
Yes it is in #369

**Comment by i-make-robots** [comment]
Okay... trying to implement this is not easy.  the layout of the other buttons (the whole Select* system) is fighting the layout that it should have.
