### ISSUE TITLE
Improve log for diagnostic

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#434]
**Is your feature request related to a problem? Please describe.**
Recent discussions on discord show that some information are missing for user and developers to help each other.

**Describe the solution you'd like**
- I think of adding the version of makelangelo when the version of marlin is detected in the output of the robot will help.
- makelangelo should also detect when the robot says `echo:Home XY First` and display a dialog box to the user.
- same thing when makelangelo logs `MarlinInterface did not find 0`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by i-make-robots** [comment]
Master branch I turned on logging of all marlin to app conversation.  that will capture the marlin version in the first message.

I thought Makelangelo version was listed above the system settings at the start of the log file, but you're right!  I don't find it.

**Comment by coliss86** [comment]
I was saying about adding the version of makelangelo in the debug output of the robot:
![image](https://user-images.githubusercontent.com/23615562/148296654-596200cb-2063-47f1-950c-d0b3a227cf1b.png)

it is already in the startup log of the application: 
![image](https://user-images.githubusercontent.com/23615562/148296748-ec6b905e-664c-4623-9293-2fe2105d18b2.png)

**Comment by i-make-robots** [comment]
Yes, yes.  So everything here is already implemented.  Let's leave this open for a bit in case new ideas come up.

**Comment by i-make-robots** [comment]
Nothing?  Cool.
