### ISSUE TITLE
"robot controls > advanced controls > home" does not unlock draw control buttons

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#446]
**Steps to make the bug happen**

**What was supposed to happen**
A clear and concise description of what happens instead.

**Platform (please complete the following information):**
 - 7.31.0 bugfix
 - Windows
 - M5

**Log file**
Makelangelo software should generate a log.txt file.  Please paste or link it here.

**Additional context**

**Comment by coliss86** [comment]
Is the robot connected when you click on the home button ?

**Comment by i-make-robots** [comment]
Of course.
