### ISSUE TITLE
MenuBar : File -> Save = Error (but file created and seems ok ...)

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#460]
A throw out of context ? 

https://github.com/MarginallyClever/Makelangelo-software/blob/33cb237f34463936f6ab07ce84339bff82bf416b/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/TurtleFactory.java#L75

**Comment by i-make-robots** [comment]
What format were you saving as?  Please show steps to recreate the error.

**Comment by PPAC37** [comment]
My apologies (bad presentation of the bug)
Makelangelo 7.31.0 (master)
(Possibly do a "Generate art" but does not change anything)
Then, menu bar "File" -> "Save"
![image](https://user-images.githubusercontent.com/94939582/150410892-adc87f89-748d-45fe-8c77-9a1bd2ce95b7.png)

On save file dialog : 

* filename ex "test_d"
* Files of Type: "DXF R12" or "Scalable Vector Graphics 1.1" ( same result)
* click "Save"

![image](https://user-images.githubusercontent.com/94939582/150410935-d2c91658-9dc4-4183-91cb-175e44050140.png)

Error 
TurtulFactory could not save '...'.

But if you check the destination, the file was created and looks correct...

**Comment by i-make-robots** [comment]
I confirm this is replicable.

**Comment by i-make-robots** [comment]
fixed on both branches.
