### ISSUE TITLE
Red line 

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#465]
**Steps to make the bug happen**
1. Go to 'Makelangelo, Select the machine "custom"

It may be a bug : what are the red lines ?
![image](https://user-images.githubusercontent.com/23615562/150416424-a14ccad9-1180-4326-bd7c-f74990e9fa1e.png)

**Comment by PPAC37** [comment]
To me, the red lines basically look like the achievable limit for a given belt distance ...
But yes it seems that the lower part is to be adjusted to the limits of the sides or the reverse ...

**Comment by i-make-robots** [comment]
@PPAC37 You are correct.  This is not a bug.  I will turn it off.
