### ISSUE TITLE
LoadGcode with flavor choise ( marlin-polargraphe gcode vs makelangelo-firmware gcode)

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#483]
**Is your feature request related to a problem? Please describe.**
To be able to loadGcode for marlin-polargraphe ( as the curent implementation dont use G0 to penUp and G1 to penDown turtle ... but the Z value ( adapted for makelangelo-firmware gcode but not for the marlin-firmware gcode ...) )

https://github.com/MarginallyClever/Makelangelo-software/blob/abe3a1dfb869e256b819a3edff6c662a72e6377f/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadGCode.java#L124-L130

**Describe the solution you'd like**
2 interpretation 

1 only for the marlin-polargraphe flavored gcode

adding something like 
G0 -> PenUp
G1 -> PenDown
( and removing the PenUp/Down on Z change )

```
					if(gCode==0 || gCode==1) {
					        // Only for marlin-polargraph flavored .gcode
						if ( gCode == 0){
						    turtle.penUp();
						}else{
						    turtle.penDown();
					  
						}
						// Only for Makelangelo-firmware flavored .gcode
//						if(nz!=oz) {
//							// z change
//							if(turtle.isUp()) turtle.penDown();
//							else turtle.penUp();
//							oz=nz;
//						}
```
to get the result (on the right) and not  the result (on the left, only moves)
![image](https://user-images.githubusercontent.com/94939582/151463630-934dccb0-18cf-470f-ba29-58c34e8ddd08.png)

And
1 only for Makelangelo-firmware gcode
Keep the actual LoadGcode version 

**Describe alternatives you've considered**
No post compatibilitie. Adapt to correctly load gcode marlin-polargraph.

**Additional context**

**Comment by i-make-robots** [comment]
Mmm... I think it's easier to write a single app that does the string replacement for the few people who need it.  should auto detect which type of file it is looking at and present the user with a confirmation button.  Probably doesn't need a progress bar.  Might want to have dialog for up and down angles.  But I don't think it belongs in Makelangelo Software.

**Comment by PPAC37** [comment]
I hadn't thought of the external transformation program. Thank you.

In fact, the only flaw with the current implementation of Makelangelo is that it currently generates .gcode for marlin-polargraph and interprets with LaodGCode .gcode for Makelangelo-polargraph.
Seems inconsistent to me...
But it's not a priority. So I'm closing the issue here and I'm making one on my fork so as not to forget the days when I would have done everything I need to end up here.)

**Comment by i-make-robots** [comment]
> In fact, the only flaw with the current implementation of Makelangelo is that it currently generates .gcode for marlin-polargraph and interprets with LoadGCode .gcode for Makelangelo-polargraph.

so it writes and reads the same format?  I am confused why that is a bad thing.

**Comment by PPAC37** [comment]
>so it writes and reads the same format? I am confused why that is a bad thing.

Sorry i have poorly explain myself.

Not currently save gcode in marlin flavor but read as polorgraph flavor (to understand you have to try saving in GCode from Makelangelo then re-read this .gcode file with Makelangelo...)
![image](https://user-images.githubusercontent.com/94939582/151611028-f42faefe-1deb-407c-be25-82c5646ad7c8.png)
![image](https://user-images.githubusercontent.com/94939582/151611038-b7f8991d-2b18-46f5-a149-aefc8bb344d6.png)

**Comment by PPAC37** [comment]
Oups bad second image
the one i get
![image](https://user-images.githubusercontent.com/94939582/151611123-7790e643-85c0-4d38-8484-23f6e8c284e4.png)

**Comment by i-make-robots** [comment]
see https://github.com/MarginallyClever/Makelangelo-software/pull/487
