### ISSUE TITLE
Plotter Controls > Advanced Controls render outside parent bounding limits

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#489]
**Steps to make the bug happen**
1. Load any image or vector
2. Open plotter controls
3. expand advanced controls

**What was supposed to happen**
tabs inside advanced control are now hanging off the edge of the window and cannot be seen.  "DRAW_LINE" in program window appears as "RAW_LINE".

**Platform (please complete the following information):**
 - Version: 7.31.x
 - Windows

**Additional context**
Also I see the plotter controls are called "robot controls" and so is the jog panel!  Two things with different jobs and the same name?!

**Comment by PPAC37** [comment]
Same for me (on linux)
If we resize the width, larger then smaller then there is a placement defect 
![image](https://user-images.githubusercontent.com/94939582/151641714-6298fade-41d1-40e2-9b8e-2fdda5028d9a.png)

(but if we click again on the tabs (change tab and come back) this is corrected...)

> Also I see the plotter controls are called "robot controls" and so is the jog panel! Two things with different jobs and the same name?!

sorry dont get it ... you are talking about the title of the dialogue and the title of a tab in Advanced controls  which are "identical" on my capture or something else.

**Comment by i-make-robots** [comment]
> sorry dont get it ... you are talking about the title of the dialogue and the title of a tab in Advanced controls which are "identical" on my capture or something else.

Yes, exactly.  They are different, they should not be named the same.

**Comment by PPAC37** [comment]
```
<string>
		<key>PlotterControls.Title</key>
		<value>**Robot controls**</value>
		<hint>title</hint>
	</string>
...
	<string>
		<key>PlotterControls.JogTab</key>
		<value>**Robot controls**</value>
		<hint>panel tab title</hint>
	</string>
```

**Comment by coliss86** [comment]
I'll fix it
