### ISSUE TITLE
Files opening

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#493]
**Is your feature request related to a problem? Please describe.**
When opening a file, you you have to click twice to have the choose file dialog : In the menu and on the popup that just appeared.
In gimp or inkscape, when you click on the "Open..." you can directly select the file.

Moreover, in gimp, by default the file filter is set to every type of file supported. here, you have to select the file type in svg for example and then you can select the file.

Besides, in the case of svg files, the LoadFilePanel is empty, so I think it is not needed.

**Describe the solution you'd like**
I would like that the LoadFilePanel don't show before the selection file window.
I also would like that the selection filter match all type of file, eg: dxf, svg, png jpeg... and be selected by default

**Describe alternatives you've considered**
none

**Comment by coliss86** [comment]
Here is a first prototype of the "all file types": 
![image](https://user-images.githubusercontent.com/23615562/151680872-d7bd46b5-f908-4d62-bfba-2847f4aa50c1.png)

**Comment by PPAC37** [comment]
i like it ! 

![image](https://user-images.githubusercontent.com/94939582/151682905-e4a89606-1b25-4c02-94cf-1d7f29770452.png)
![image](https://user-images.githubusercontent.com/94939582/151682906-2d47a626-df55-4bdd-b93e-9881525e0b06.png)
