### ISSUE TITLE
🐛 desktop.setQuitHandler() causes java.lang.UnsupportedOperationException on windows

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#501]
**Steps to make the bug happen**
1. start app in windows

**Additional context**

> UnsupportedOperationException - if the current platformdoes not support the Desktop.Action.APP_QUIT_HANDLER action

There does not appear to be a clean way to detect if the action is supported before calling the method.  Doh!

**Comment by coliss86** [comment]
Can you post the full stack trace please ?
