### ISSUE TITLE
Application in german when launching for the first time

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#505]
**Steps to make the bug happen**
1. Start the app on a brand new computer: it is in german. Quite hard to find the settings to change the language ;)

**What was supposed to happen**
The default language should be english

**Platform (please complete the following information):**
 - Version: master
 - OS: windows
 - Robot model (if any): [e.g. Makelangelo 5]

**Log file**
none

**Comment by PPAC37** [comment]
So no chose language dialog at the first run ?
![image](https://user-images.githubusercontent.com/94939582/151874024-c55a3ffb-1988-4f53-b215-d261676f733a.png)
( if i delete my ~/.java/.userPrefs/DrawBot/Language i get this . But strangly this dialgue is not seen as a "windows aplication" in my desktop manager so i dont have a spécific icone in my systeme application bar ... )

**Comment by coliss86** [comment]
Nop, nothing :'(
I tried on Windows.

**Comment by PPAC37** [comment]
And no log ?



https://github.com/MarginallyClever/Makelangelo-software/blob/98686f479880423c293cb2ade333754f8d3b1fcb/src/main/java/com/marginallyclever/makelangelo/Makelangelo.java#L1008-L1010

https://github.com/MarginallyClever/Makelangelo-software/blob/98686f479880423c293cb2ade333754f8d3b1fcb/src/main/java/com/marginallyclever/makelangelo/Translator.java#L59-L81

https://github.com/MarginallyClever/Makelangelo-software/blob/98686f479880423c293cb2ade333754f8d3b1fcb/src/main/java/com/marginallyclever/makelangelo/makelangeloSettingsPanel/LanguagePreferences.java#L42-L55

**Comment by PPAC37** [comment]
Also not the problem here but was wondering where the prefrences are store in other OS type and version  ?

**Comment by coliss86** [comment]
I'll try again asap.
thank for pointing where to look for :)

**Comment by coliss86** [comment]
I did not get time to test it again

**Comment by coliss86** [comment]
I tried again and was not able to reproduce the issue. Closing it.
