### ISSUE TITLE
Features supported on Marlin ?

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#531]
**Is your feature request related to a problem? Please describe.**
Is there a way to retrieve the bed width and height, belt length and home position when connecting to the robot with some Gcode ?
I think it will be useful to help people to debug there settings and to help the support.

**Describe the solution you'd like**
Don't know

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by i-make-robots** [comment]
No.  DIY makers will always have these challenges.  It's the same in the 3D printing forums, too.  Even if you could move motors and bump off both sides there's no guarantee the user set the right microstepping, used the right pulleys, etc.  there's no good way to use the timing belt as a ruler to measure the distance between motors.

Part of the advantage of the kits I sell is that they don't have to do any of this BS.

**Comment by PPAC37** [comment]
There is #define M115_GEOMETRY_REPORT (required for some BTT TFT screen ) in configuration_adv.h to have the bed size dimentions ( and offset ) with https://marlinfw.org/docs/gcode/M115.html 

https://github.com/MarginallyClever/Marlin-polargraph/blob/501b30cf9b635634fa064a91bd75741910f37f41/Marlin/Configuration_adv.h#L3738

Activated it get you something like (Repetier Host log)
the "area:" part (but subject to possible offset definition ...) 
~~~
03:26:40.089 : N13 M115*20
03:26:40.107 : N14 M220 S100*84
03:26:40.107 : N15 M221 S100*84
03:26:40.107 : N16 M111 S6*80
03:26:40.107 : N17 T0*12
03:26:40.107 : FIRMWARE_NAME:Marlin bugfix-2.0.x (Jan 26 2022 21:16:50) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:PPAC Polargraph Makelangelo 5 like EXTRUDER_COUNT:0 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
03:26:40.107 : Cap:SERIAL_XON_XOFF:0
03:26:40.107 : Cap:BINARY_FILE_TRANSFER:0
03:26:40.108 : Cap:EEPROM:1
03:26:40.108 : Cap:VOLUMETRIC:0
03:26:40.110 : Cap:AUTOREPORT_POS:0
03:26:40.110 : Cap:AUTOREPORT_TEMP:0
03:26:40.110 : Cap:PROGRESS:0
03:26:40.110 : Cap:PRINT_JOB:1
03:26:40.110 : Cap:AUTOLEVEL:0
03:26:40.111 : Cap:RUNOUT:0
03:26:40.115 : Cap:Z_PROBE:0
03:26:40.115 : Cap:LEVELING_DATA:0
03:26:40.115 : Cap:BUILD_PERCENT:0
03:26:40.115 : Cap:SOFTWARE_POWER:0
03:26:40.115 : Cap:TOGGLE_LIGHTS:0
03:26:40.118 : Cap:CASE_LIGHT_BRIGHTNESS:0
03:26:40.118 : Cap:EMERGENCY_PARSER:0
03:26:40.118 : Cap:HOST_ACTION_COMMANDS:0
03:26:40.118 : Cap:PROMPT_SUPPORT:0
03:26:40.122 : Cap:SDCARD:1
03:26:40.122 : Cap:REPEAT:1
03:26:40.123 : Cap:SD_WRITE:1
03:26:40.123 : Cap:AUTOREPORT_SD_STATUS:0
03:26:40.123 : Cap:LONG_FILENAME:0
03:26:40.123 : Cap:THERMAL_PROTECTION:1
03:26:40.127 : Cap:MOTION_MODES:0
03:26:40.127 : Cap:ARCS:1
03:26:40.127 : Cap:BABYSTEPPING:0
03:26:40.128 : Cap:CHAMBER_TEMPERATURE:0
03:26:40.128 : Cap:COOLER_TEMPERATURE:0
03:26:40.130 : Cap:MEATPACK:0
03:26:40.134 : area:{full:{min:{x:-532.00,y:-500.00,z:0.00},max:{x:532.00,y:500.00,z:200.00}},work:{min:{x:0.00,y:0.00,z:0.00},max:{x:1064.00,y:1000.00,z:200.00}}}
03:26:40.134 : ok
03:26:40.139 : ok
03:26:40.139 : echo:Unknown command: "M221 S100"
03:26:40.139 : ok
03:26:40.139 : echo:DEBUG:INFO,ERRORS
03:26:40.139 : ok
03:26:40.139 : ok

~~~

For the belt lenght as this is new in marlin, not reported in the current implementation...

**Comment by i-make-robots** [comment]
Marlin is well familiar with the cartesian limits.  it knows very little about the polargraph limits (belt length)
