### ISSUE TITLE
Load file Scratch 3 

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#534]
**Steps to make the bug happen**
Try to open a Scratch 3 project save as a local file ( extension .sb3 ).
https://scratch.mit.edu/projects/641318749
[PPAC37_Makelangelo_test_02_koch_curve_03.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8030735/PPAC37_Makelangelo_test_02_koch_curve_03.zip)

**What was supposed to happen**
* The Scratch file is open and render

A clear and concise description of what happens instead.
* Dialog error message whith Exceptions ...

 ( after changing the TurtleFactory isValidExtension 
https://github.com/MarginallyClever/Makelangelo-software/blob/ab4bf229e44eb53e146fd547569e607ceb83a59d/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/TurtleFactory.java#L43

by 
~~~
if(filename.toLowerCase().endsWith(e.toLowerCase())) return true;
~~~
 to accept lower case extension "sb3"
and correcting a cast Exception ...

https://github.com/MarginallyClever/Makelangelo-software/blob/ab4bf229e44eb53e146fd547569e607ceb83a59d/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java#L335

with
~~~
value = Double.parseDouble(details.get(1).toString());
~~~

)

~~~
java.lang.ClassCastException: class org.json.JSONObject$Null cannot be cast to class java.lang.String (org.json.JSONObject$Null is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')	
~~~
line 
https://github.com/MarginallyClever/Makelangelo-software/blob/ab4bf229e44eb53e146fd547569e607ceb83a59d/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java#L196
 
**Platform (please complete the following information):**
 - Version: github master 7.31.0
 - OS: Linux Ubuntu 18.04, 
 ~~~
$ java --version
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
~~~

Is LoadFile Scratch 3 experimental (or not fully yet implemented) and this is normal 
or is this my JRE ? or something else ?

**Comment by i-make-robots** [comment]
SB3 is incomplete.  The format is MUCH more complicated than SB2.

**Comment by i-make-robots** [comment]
Do you have a sample to work from?

**Comment by i-make-robots** [comment]
[inkylinesplot.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8035208/inkylinesplot.zip)
![Capture2](https://user-images.githubusercontent.com/1464454/153264685-40c6ca08-f70f-40da-ba29-34d62e5ed897.PNG)
![Capture](https://user-images.githubusercontent.com/1464454/153264691-dd6d443b-fade-4273-8b7a-f89d6dc9b6d2.PNG)

**Comment by i-make-robots** [comment]
first problem, case sensitive file extensions in `TurtleFactory.isValidExtension()` fixed in my branch.

**Comment by i-make-robots** [comment]
First plot success in eb88f443

**Comment by i-make-robots** [comment]
It works with https://github.com/MarginallyClever/Makelangelo-software/files/8035208/inkylinesplot.zip
OP sample is much more complex.

**Comment by PPAC37** [comment]
Some minor changes and rendering of motion blocks, added in #537 

The management/interpretation of procedure and procedure call in a Scratch project remains out of reach for the moment ... (and it's been a while since I played to make an interpreter that needs a stack of calls and variable state stack so I'm rusty in their implementations)

**Comment by i-make-robots** [comment]
![Capture4a](https://user-images.githubusercontent.com/1464454/153476787-fb08ea38-cc78-492f-a727-67615a6f7416.PNG)
![Capture4b](https://user-images.githubusercontent.com/1464454/153476796-7e083880-3d88-4f51-a2fd-2f764562fdd5.PNG)

**Comment by PPAC37** [comment]
I take my hat off to you! / Respect!
Well done!

**Comment by PPAC37** [comment]
unfortunately, now inkylinesplot.sb3 gives me an exception when loading it.
~~~
2022-02-11 08:02:07,751 ERROR c.m.m.makeArt.io.LoadFilePanel - Failed to load /home/q6/0_mcM_test/scratch3/inkylinesplot.sb3 
org.json.JSONException: JSONObject["VARIABLE"] not found.
	at org.json.JSONObject.get(JSONObject.java:572)
	at com.marginallyclever.makelangelo.makeArt.io.vector.LoadScratch3.findInputInBlock(LoadScratch3.java:457)
	at com.marginallyclever.makelangelo.makeArt.io.vector.LoadScratch3.setVariableTo(LoadScratch3.java:385)
	at com.marginallyclever.makelangelo.makeArt.io.vector.LoadScratch3.parseScratchCode(LoadScratch3.java:241)
	at com.marginallyclever.makelangelo.makeArt.io.vector.LoadScratch3.readScratchInstructions(LoadScratch3.java:203)
~~~

Also, in the case of a "poorly" done/"not clean" scratch project, (for example, if we leave a variable lying around, 
![image](https://user-images.githubusercontent.com/94939582/153551280-12d703b9-f3da-44e3-99bd-99862db28bd2.png)

https://scratch.mit.edu/projects/642635174

we have some cast Exceptions at

https://github.com/MarginallyClever/Makelangelo-software/blob/f1da7ada92cc6bc95d8711a1dabdc3ac7386af07/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java#L195

solution ? 
~~~
	Object blocks_get_h = blocks.get(k);
			if ( ! ( blocks_get_h instanceof JSONObject )){
				// // TODO somethinge is not what expected ... maybe a lost variable in the scratch projet ...
				logger.debug("not expected: {} instanceof::{}",blocks_get_h,blocks_get_h.getClass().toString());
			}else{
...

~~~
and same at
https://github.com/MarginallyClever/Makelangelo-software/blob/f1da7ada92cc6bc95d8711a1dabdc3ac7386af07/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java#L613

**Comment by PPAC37** [comment]
Cant find VARIABLE :
[StrangeOrbit remix.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8051300/StrangeOrbit.remix.zip)
![image](https://user-images.githubusercontent.com/94939582/153662694-d83c978a-f6ba-41e4-9707-23f52e028538.png)


A casting exception (due to a variable lost in the project), and also an infinite loop (yes it's normal that this creates an infinite loop when reading, but that tells me that the infinite loop should not be implemented , or just loop it once and put a warning ... and normally illustrate the 90° orientation difference between Scratch and turtle. :
[base_pen_axis_lost_var_and_infinit_loop.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8051301/base_pen_axis_lost_var_and_infinit_loop.zip)
![image](https://user-images.githubusercontent.com/94939582/153662440-ad5ea9a6-8c1d-417b-9069-d2c9557fcba3.png)

**Comment by PPAC37** [comment]
And a starnge one ... input0 not found 
[TurtleArt - never ending flower remix copy.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8051390/TurtleArt.-.never.ending.flower.remix.copy.zip)
![image](https://user-images.githubusercontent.com/94939582/153663992-45f40edf-0952-46f4-ac97-ae0f0ce652b1.png)

**Comment by i-make-robots** [comment]
Latest update appears to pass all cases.  Thank you for the great puzzles!
new translation key `LoadScratch3.foreverNotAllowed` to warn users.  Easiest way for me was to just say no.

**Comment by PPAC37** [comment]
![image](https://user-images.githubusercontent.com/94939582/153704530-a2a0210e-9fa7-433c-ac64-9194c9dc4810.png)

Magnificent! I'm having fun with Scratch (working on my algorithmic)!
and Makelangelo gives me great results.

The essential scratch uses seem to be implemented.

I dare to ask
I have two features that will be user friendly but the last one is not without difficulty/risk.

1 - Color : As there is possibility in a Scratch project to define the color of the pen, it seems possible to take it into account in turtle to allow multi color (as in the graph paper generator).

2 - "parametric variables". As it is possible to define in the scratch monitor, variables with a Slider bar, to modify their value, a Dialoge/JPanel which will allow them to be modified (a bit like what is done with images or turtle generators, but there the SelectSlider would be dynamicaly built based on the visible variables, with a Slider bar, in the "monitor" of the scratch project. (this query seems like too much coding but eventually maybe, when we have settled most important things... :) )

**Comment by PPAC37** [comment]
For colors if you have red/green 3D glasses a basic 3D anaglyph test
![image](https://user-images.githubusercontent.com/94939582/153712846-410d37f9-4eeb-46ef-ad90-7b5e015a3564.png)

https://scratch.mit.edu/projects/643301613
[anaglyphe_000.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8053436/anaglyphe_000.zip)

**Comment by PPAC37** [comment]
operator modulo seem to be missing.
![image](https://user-images.githubusercontent.com/94939582/153715238-ab2dfd93-75f5-4ba5-a5db-de8ef5953536.png)
https://scratch.mit.edu/projects/643326693
[modulo_and_round.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8053605/modulo_and_round.zip)

**Comment by i-make-robots** [comment]
I haven’t found the color field yet. Could be done.
Sliders would mean a two step loading process, very complex from here.
Mod can happen.

**Comment by PPAC37** [comment]
setAngle value in Turtle do not match scratch DIRECTION orientation ...
![image](https://user-images.githubusercontent.com/94939582/153720815-3a2ca5d5-c2b8-4393-9ab6-4ae76698c250.png)

https://scratch.mit.edu/projects/643375721/
[orientation.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8054075/orientation.zip)
![image](https://user-images.githubusercontent.com/94939582/153720780-1ac36755-fcfb-4275-9fc2-856e92f3348b.png)

**Comment by i-make-robots** [comment]
I suspect the starting orientation is wrong.
