### ISSUE TITLE
Add the commit hash in the version

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#543]
**Is your feature request related to a problem? Please describe.**
@PPAC37  suggest to add the commit hash somewhere in the app to better know which version is used

**Describe the solution you'd like**
I will add this info in the file `src/main/resources/makelangelo.properties`

**Describe alternatives you've considered**
None, this is purpose of `src/main/resources/makelangelo.properties`

**Additional context**
none

**Comment by PPAC37** [comment]
:) When I registered on git I wanted PPAC as my username but it was already taken... (@ppac sorry for the inconvenience.)

**Comment by coliss86** [comment]
good catch, I corrected the description
