### ISSUE TITLE
Machine width and height not loading correctly

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#544]
**Steps to make the bug happen**
1. change plotter width and height
2. quit and restart
3. plotter width and height (white lines) are correct for value loaded but loaded value is not value set in previous session.

**What was supposed to happen**
save and load consistency.  unit test fail?

**Platform (please complete the following information):**
 - 7.31.0
 - OS: Windows

**Comment by PPAC37** [comment]
> save and load consistency. unit test fail?

It look like we just have forget to load the pref config a the class initialisation (loadConfig used only in the test class) ...
https://github.com/MarginallyClever/Makelangelo-software/blob/ee8c91ab913c9d201104670a8d8ea86f901b8050/src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettings.java#L77-L95

adding a the end 
~~~

		loadConfig(robotUID);// to load back Pref saved value ... but is this the good way (Overridable methode call in the constructor) and  suffisent for all case ? (when we will use setRobotUID )
	
~~~
do the trick ... but as long as 
https://github.com/MarginallyClever/Makelangelo-software/blob/ee8c91ab913c9d201104670a8d8ea86f901b8050/src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettings.java#L157-L159
is only used in the test ...

**Comment by i-make-robots** [comment]
changed defaults in 3cb5d444 to match m5

**Comment by coliss86** [comment]
Thanks @PPAC37 for your analysis.
