### ISSUE TITLE
Move the pen out of drawing at the end of the drawing

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#552]
**Is your feature request related to a problem? Please describe.**
When a drawing is finished, I would like that the pen is moved out of the drawing area, like to the home position.

**Describe the solution you'd like**
In SaveGCode, it is pretty straight forward: https://github.com/coliss86/Makelangelo-software/blob/bc9dd294a2d0fed1de1340b3722262f0cbc84be3/src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/SaveGCode.java#L102
add a `out.write("G28\n");  // go home`

But in `MarlinPlotterInterface`, I don't know how to detect the end of the drawing.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by i-make-robots** [comment]
For a while we were moving to the top left corner after drawing. Would that do? Keeps the pen and belt out of the way if you’re taking a picture.

**Comment by coliss86** [comment]
nice ! how do you calculate this position ?

**Comment by i-make-robots** [comment]
we know the machine size, I think I just parked it 10cm from the left edge and 15cm from the top edge.
