### ISSUE TITLE
Shortcut CTRL + C should not be mapped to something else than "copy"

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#555]
**Is your feature request related to a problem? Please describe.**
CTRL + C is mapped to open control but in every other app it is mapped to copy. As the functionality copy/paste does not exist, it may not be a problem but I suggest to change it something else like to CTRL + T.
What do you think @PPAC37  ?

**Comment by PPAC37** [comment]
Yes you are right. When I made the shortcut Ctrl C I should have tilted. Thanks for pointing out.

**Comment by coliss86** [comment]
ok, I just made the changes in https://github.com/MarginallyClever/Makelangelo-software/pull/554

**Comment by coliss86** [comment]
Fix in https://github.com/MarginallyClever/Makelangelo-software/pull/554
