### ISSUE TITLE
File cleanup ?

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#562]
**Is your feature request related to a problem? Please describe.**
I think some files are not needed anymore:
- [x] Makelangelo.doxyfile
- [x] other-resources/favicon.xcf
- [x] src/main/java/com/marginallyclever/convenience/GridBagConstraintsLabel.java
- [x] src/main/java/com/marginallyclever/convenience/GridBagConstraintsValue.java
- [x] src/main/java/com/marginallyclever/convenience/Profiler.java
- [x] src/main/java/com/marginallyclever/convenience/SpringUtilities.java
- [x] src/main/java/com/marginallyclever/util/package-info.java
- [x] src/main/art

**Describe the solution you'd like**
I would like to delete them

**Comment by PPAC37** [comment]
Also 

(double ?)
* [ ] https://github.com/MarginallyClever/Makelangelo-software/blob/master/src/main/art/makelangelo5-motors.png
* [ ] https://github.com/MarginallyClever/Makelangelo-software/blob/master/src/main/art/makelangelo5.png
(? may be better to store it elsewhere (not in src) )
https://github.com/MarginallyClever/Makelangelo-software/blob/master/src/main/art/makelangelo5.xcf

(some files (*.sb2, *.svg ) don't seem to be used in any test (but to be checked) maybe better to store them somewhere else?)
https://github.com/MarginallyClever/Makelangelo-software/tree/master/src/test/resources

**Comment by coliss86** [comment]
no, keep src/test/resources, I'm planning to add unit test with those files

**Comment by i-make-robots** [comment]
I have no issue with removing the suggested files.  Only keep what @coliss86 wants.

**Comment by i-make-robots** [comment]
there shouldn't be an art folder.  if there is, it's probably meant to be the original source material and belongs in other-resources, which should be .ignored.
