### ISSUE TITLE
Bad correction Scratch3 pointInDirection

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#564]
Sorry, I was wrong.
The current implementation of Scratch3 pointInDirection does not have a -90° difference with Turtle.setAngle.

It's rather (only for pointInDirection ) an axial symmetry of an axis having an angle of 45°... 

and there I don't know if it's Turtle's setAngle 
https://github.com/MarginallyClever/Makelangelo-software/blob/046682f054870411f4b554a18312204f33fe0823/src/main/java/com/marginallyclever/makelangelo/turtle/Turtle.java#L202-L207
or if it's really that...

(if I make the correction in LoadScratch ...) I have trouble seeing clearly to apply this transformation in an elegant way to an orientation in °

https://scratch.mit.edu/projects/647531000

[debug_orientation_c_t_s_ap_d_fus.zip](https://github.com/MarginallyClever/Makelangelo-software/files/8103721/debug_orientation_c_t_s_ap_d_fus.zip)

Rendered under scratch
![image](https://user-images.githubusercontent.com/94939582/154836896-b6c57aa4-9c85-4aa5-a010-48ea7b911fbd.png)

Rendered under Makelangelo (master) via LoadScratch3 
![image](https://user-images.githubusercontent.com/94939582/154836905-dd0fdd33-7f85-4c42-ae25-2a6b4b00e4c1.png)

(n.b.: don't pay attention to the colors, I'm trying to implement pen_changePenColorParamTo and pen_changePenColorParamBy and I still have small adjustments to do in my calculations between RGB color and HSB color...)

**Comment by PPAC37** [comment]
![image](https://user-images.githubusercontent.com/94939582/154840367-2434e510-3822-4ee6-91dc-125920bf06b5.png)

**Comment by coliss86** [comment]
@PPAC37 can you have a look at the PR #567 which add unit test for scratch files.
This PR is based on the work on #563 and show duplicates code between the both, as soon as #563 is merged, I'll update #567.
When you'll make your fix, you should add a new test in LoadScratch3Test.java to make sure the expected behaviour does not change over time

**Comment by PPAC37** [comment]
I'm really not fresh today, it took me all this time to finish with `myTurtle.setAngle(90.0-v);` instead of `myTurtle.setAngle(v-90.0);`
