### ISSUE TITLE
LoadSVG, an approximation for CubicCurve, generateCurvePoints(...);

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#578]
**Is your feature request related to a problem? Please describe.**
Resolution.
I know it's a tricky compromise to find. And that it depends on the "fineness" of the original SVG and therefore probably not suitable for other SVGs which do not have the same "fineness".

**Describe the solution you'd like**
Find a way to have the ideal resolution in any case ...

**Describe alternatives you've considered**
Maybe to avoid complicating, a parameter that can be overloaded/redefined when launching Makelangelo via command line argument?

**Additional context**

https://github.com/MarginallyClever/Makelangelo-software/blob/094ec4a87595787d584735dd32a56112701a648a/src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadSVG.java#L374

from 0.1 to 0.01 to 0.001
![image](https://user-images.githubusercontent.com/94939582/155336635-98436a33-8442-47bb-8602-4ecd94f73dd9.png)

![Flourish-Butterfly-Silhouette](https://user-images.githubusercontent.com/94939582/155336705-b69b0172-774a-4274-b23b-16040eeb367e.svg)
source https://freesvg.org/

**Comment by PPAC37** [comment]
well this is definitely going to be a headache...
So we will avoid touching it at 0.1 because at 0.001 I get
![image](https://user-images.githubusercontent.com/94939582/155341049-90986c22-31ab-4835-8c6e-2f567388ed74.png)
![1487426692](https://user-images.githubusercontent.com/94939582/155341120-0eecf1ce-5c33-42b9-92a8-1e990c03c04b.svg)

**Comment by i-make-robots** [comment]
I wonder if the SVG initially is very small.  this would mean a very small number of points in a curve.  then the SVG is scaled up to fill the paper and the problem becomes obvious.  If it was the other way around - load the SVG huge and then bring it down - there would be too many points in each curve.  Can't win!
