### ISSUE TITLE
FileName proposition on Save*

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#581]
**Is your feature request related to a problem? Please describe.**
Have proposed a file name for saving (SaveSVG / SaveDXF / SaveGCode) if comes from an image/dxf/svg/gcode/sb3 file, the name of the open file.

**Comment by i-make-robots** [comment]
https://github.com/MarginallyClever/Makelangelo-software/discussions/626  idea #1: add a name field to turtles.

**Comment by PPAC37** [comment]
I am for it ! 
Do you want me to reopen https://github.com/MarginallyClever/Makelangelo-software/pull/573 ?
