### ISSUE TITLE
Plotter settings Save or cancel do not close the dialog and need a global scrollBar if resized

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#585]
all in the title.

**Comment by coliss86** [comment]
I would like to see a "reset" button instead of "cancel". maybe a third button "close" to close the window

**Comment by i-make-robots** [comment]
I hate extra buttons.  the [x] button is enough.  We can make the dialog non-resizable?  `setResizable(false);` ?

**Comment by i-make-robots** [comment]
More thoughts on this...   like Prusa slicer, there should be a table of profiles.  a profile is a specfic set of plotter settings.

- [ ] with defaults for some machines (m5, m3.3, huge, etc).
- [ ] user can choose a profile and 
- [ ] then save it as a new design and tweak it.  
- [ ] user can't delete the default profiles.  
- [ ] user CAN delete custom profiles.
- [ ] all profiles can be saved to disk for unit testing/backups.
- [ ] user can swap between profiles non-destructively.
- [ ] plotter rendered in preview controlled by profile.

**Comment by i-make-robots** [comment]
also overlaps with #603
