### ISSUE TITLE
Plotter settings Pen Up/Down color usage ( implementation ) 

### ISSUE THREAD

**Issue by PPAC37** [MarginallyClever/Makelangelo-software#598]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/94939582/156651629-77b50f0c-66fd-4f23-b8ae-ae8492db942e.png)
Currently not taken int account in the preview and in plotter control
(as pen size)

**Comment by i-make-robots** [comment]
I cannot see an elegant way to set the turtle pen down color without making a public global in `Turtle` and that will almost certainly create a disaster somewhere else.  easy to implement, hard to test.
