### ISSUE TITLE
Bumping version number breaks gcode exports

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-software#616]
**Steps to make the bug happen**
1. Change pom.xml <version> value.
2. Maven > package

**What was supposed to happen**
Gcode is exporting the version of makelangelo.  This breaks all gcode tests every time the version is changed.

**Platform (please complete the following information):**
 - Version: 7.32.0

**Log file**
```
[ERROR] Failures: 
[ERROR]   SaveGCodeTest.saveMultiColor:38->verifySavedFile:61 iterable contents differ at index [0], expected: <;Generated with Makelangelo 7.32.0> but was: <;Generated with Makelangelo 7.32.1>
[ERROR]   SaveGCodeTest.saveTurtle:33->verifySavedFile:61 iterable contents differ at index [0], expected: <;Generated with Makelangelo 7.32.0> but was: <;Generated with Makelangelo 7.32.1>
```

**Additional context**
If there's a process to regenerate the gcode then please document it.

**Comment by carl1961** [comment]
@i-make-robots , I know nothing with programing, I just copy and paste things, LOL  but maybe this will help?

https://www.programmerall.com/article/4220817353/
