### ISSUE TITLE
Makelagelo software dmg not opening on OSX 13 Ventura 

### ISSUE THREAD

**Issue by NicoMiceli** [MarginallyClever/Makelangelo-software#671]
**Steps to make the bug happen**

I'm on the new OSX version 13, and when I download and install the dmg, I get the error ""Makelangelo” is damaged and can’t be opened. You should move it to the Trash."

 ![image](https://user-images.githubusercontent.com/1584504/200212105-96d683e5-15c2-48c2-9fc5-3a72895e58ec.png)

I saw the workaround here https://mcr.dozuki.com/Guide/1.+How+to+use+Makelangelo+Software+7.32+/39?lang=en#s434
However, I do not see the ability to approve that file. 

See the new settings screen here right after I tried to open the makelangelo 7.32.0:
![image](https://user-images.githubusercontent.com/1584504/200212403-537d9021-e31c-43bc-bd6b-64b265ab2913.png)

**What was supposed to happen**
I was expecting to see the error based don't the docs, but in the new version of OSX, I am not seeing the ability to approve the file. 

**Platform (please complete the following information):**
 - Version: 13.0 (22A380)
 - OS: OSX

**Comment by i-make-robots** [comment]
How thorough!  I love it.

Does this work?

1. In the Finder on your Mac, locate the app you want to open.
2. Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.
3. Control-click the app icon, then choose Open from the shortcut menu.
4. Click Open.
5. The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.
-- https://support.apple.com/en-ca/guide/mac-help/mh40616/mac

**Comment by NicoMiceli** [comment]
Thanks for the quick response! 

That didn't work by itself but I used that and a combination of this command: 
`sudo xattr -cr /Applications/Makelangelo.app` 
that I stumbled over in this ["old" documentation](https://mcr.dozuki.com/Guide/%5Bold%5D+How+to+use+Makelangelo+Software+7.24-7.31/5?lang=en), **and it worked!** Can that get added to the new docs [here](https://mcr.dozuki.com/Guide/1.+How+to+use+Makelangelo+Software+7.32+/39?lang=en#s434), it might help other mac folks. 

Cheers!

**Comment by i-make-robots** [comment]
Done.  Do you consider this solved to your satisfaction?

**Comment by NicoMiceli** [comment]
Definitely! Thank you.
