### ISSUE TITLE
"Flip horizontally" and "flip vertically" should be swapped.

### ISSUE THREAD

**Issue by anghelos** [MarginallyClever/Makelangelo-software#742]
**Is your feature request related to a problem? Please describe.**
"Flip horizontally" and "Flip vertically" are behaving differently than in most other image manipulation software.

**Describe the solution you'd like**
"Flip horizontally" should flip left-and-right. "Flip vertically" should flip top-and-bottom.

**Comment by i-make-robots** [comment]
I confirm the text label for each flip is swapped.  The icon is right for the action but the text is wrong.

![image](https://github.com/MarginallyClever/Makelangelo-software/assets/1464454/28ff8e3d-7cf2-4288-a40b-eedbe083845b)

**Comment by i-make-robots** [comment]
Thanks, @anghelos !
