### ISSUE TITLE
Adding multiple objects, with color changes.

### ISSUE THREAD

**Issue by anghelos** [MarginallyClever/Makelangelo-software#743]
I'd be great to be able to add multiple objects to the same canvas.

For example, I'd like to be able to add an image, select the style I want for it, then also add text.

These should be able to be moved (translated) independently.
Ideally, they could also be assigned a color, for a tool change prompt.

**Comment by i-make-robots** [comment]
A workaround is to generate them separately and then use the "import" option to merge them together.

**Comment by i-make-robots** [comment]
The other way is to build a lot of features that exist better already in other art programs link inkscape.

**Comment by anghelos** [comment]
> A workaround is to generate them separately and then use the "import" option to merge them together.

Thanks, didn't realize that "import" would not overwrite the existing artwork.

**Comment by i-make-robots** [comment]
Think of Load as `new + import`.
